-- MINGYU ARCHIVE / Supabase schema
create extension if not exists pgcrypto;
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text default 'Archive User', avatar_url text, role text not null default 'member' check(role in ('member','moderator','admin')), created_at timestamptz default now());
create table public.materials (id uuid primary key default gen_random_uuid(), title text not null, event_date date, year int generated always as (extract(year from event_date)::int) stored, category text not null, source text, participation text, mingyu_level text, link_type text, url text, note text, cover_url text, status text default 'published' check(status in ('draft','published','archived')), created_at timestamptz default now(), updated_at timestamptz default now());
create table public.comments (id uuid primary key default gen_random_uuid(), material_id uuid references public.materials(id) on delete cascade not null, user_id uuid references public.profiles(id) on delete cascade not null, body text not null check(char_length(body) between 1 and 2000), status text default 'visible' check(status in ('visible','hidden')), created_at timestamptz default now());
create table public.favorites (user_id uuid references public.profiles(id) on delete cascade, material_id uuid references public.materials(id) on delete cascade, created_at timestamptz default now(), primary key(user_id,material_id));
create table public.submissions (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id) on delete set null, title text not null, url text, event_date date, category text, note text, status text default 'pending' check(status in ('pending','approved','rejected')), created_at timestamptz default now());
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1))); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
alter table public.profiles enable row level security; alter table public.materials enable row level security; alter table public.comments enable row level security; alter table public.favorites enable row level security; alter table public.submissions enable row level security;
create policy "profiles public read" on public.profiles for select using(true); create policy "profile self update" on public.profiles for update using(auth.uid()=id);
create policy "materials public read" on public.materials for select using(status='published' or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','moderator')));
create policy "materials admin insert" on public.materials for insert with check(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','moderator'))); create policy "materials admin update" on public.materials for update using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','moderator'))); create policy "materials admin delete" on public.materials for delete using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
create policy "comments public read" on public.comments for select using(status='visible'); create policy "comments user insert" on public.comments for insert with check(auth.uid()=user_id); create policy "comments own delete" on public.comments for delete using(auth.uid()=user_id or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','moderator')));
create policy "favorites self read" on public.favorites for select using(auth.uid()=user_id); create policy "favorites self insert" on public.favorites for insert with check(auth.uid()=user_id); create policy "favorites self delete" on public.favorites for delete using(auth.uid()=user_id);
create policy "submissions self insert" on public.submissions for insert with check(auth.uid()=user_id); create policy "submissions self read" on public.submissions for select using(auth.uid()=user_id or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','moderator'))); create policy "submissions admin update" on public.submissions for update using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','moderator')));
-- After registering your own account, promote it once in SQL Editor:
-- update public.profiles set role='admin' where id=(select id from auth.users where email='YOUR_EMAIL');
